# Plik manifestu określający, które pliki wchodzą w skład bazy wiedzy.
# Tylko pliki wymienione tutaj zostaną zindeksowane w bazie wektorowej.
# Pamiętaj o wpisaniu tych plików do .github/workflows/sync.yml
# tam definiujesz które pliki podczas zmiany mają wywoływać wektoryzacje plików niżej zapisanych

files:
  - 'Linki.md'
  - 'Rekomendowane narzędzia.md'
  - 'new-knowledge/new-knowledge.md'
